[build]
  command = "echo 'Static site - no build needed'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (for future API integration)
[[redirects]]
  from = "/api/*"
  to = "https://api.modelforge.dev/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[dev]
  framework = "#static"
  targetPort = 8000
  port = 8888

# Form handling (for contact forms)
[forms]
  [forms.contact]
    fields = ["name", "email", "message"]
    to = "contact@modelforge.dev"
